[package]
name = "segmented-rs"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "list"
harness = false

[[bench]]
name = "vec"
harness = false

[features]
trace = []

